//
// Created by BinyBrion on 2019-09-14.
//

#ifndef TEXTUREATLASCREATOR_ENABLETESTS_H
#define TEXTUREATLASCREATOR_ENABLETESTS_H

#define ENABLE_SURROUNDING_BORDER_TESTS

#endif //TEXTUREATLASCREATOR_ENABLETESTS_H
