//
// Created by BinyBrion on 2019-09-14.
//

#ifndef TEXTUREATLASCREATOR_ENABLETESTS_H
#define TEXTUREATLASCREATOR_ENABLETESTS_H

#define ENABLE_TESTS

#ifdef ENABLE_TESTS
   // #define ENABLE_SURROUNDING_BORDER_TESTS
    #define ENABLE_PROJECT_LOADER_TESTS
#endif

#endif //TEXTUREATLASCREATOR_ENABLETESTS_H
