//
// Created by BinyBrion on 2019-09-14.
//

#ifndef TEXTUREATLASCREATOR_ATTRIBUTEMACROS_H
#define TEXTUREATLASCREATOR_ATTRIBUTEMACROS_H

#define WARN_UNUSED __attribute__((warn_unused_result))

#endif //TEXTUREATLASCREATOR_ATTRIBUTEMACROS_H
